# Generated by Django 4.1.2 on 2022-10-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('number_of_ratings', models.IntegerField()),
                ('authors', models.ManyToManyField(to='authors.author')),
                ('genres', models.ManyToManyField(to='genres.genre')),
            ],
        ),
    ]
