# Generated by Django 4.1.2 on 2022-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
