# Generated by Django 4.1.2 on 2023-01-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_number_of_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_ratings',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
