# Generated by Django 4.1.2 on 2023-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_date_of_birth_and_more'),
        ('books', '0005_remove_book_number_of_ratings_remove_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='authors.author'),
        ),
    ]
