# Generated by Django 4.1.2 on 2022-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
